name: CI for Project

on:
  push:
    branches:
      - main

jobs:
  phpunit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install PHP Dependencies
        run: composer install

      - name: Execute PHPUnit
        run: vendor/bin/phpunit --verbose --coverage-text
