name: CI for Project

on:
  push:
    branches:
      - main

jobs:
  phpunit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install PHP Dependencies
        run: composer install --with-dependencies

      - name: Show file composer.json
        run: cat composer.json

      - name: Execute PHPUnit
        run: php -n -dzend_extension=xdebug -dxdebug.mode=coverage ./vendor/bin/phpunit --coverage-text
